// export * from '<path>'
// export { default as <name> } from '<path>'
export { default as Demo } from './Demo'
export { default as Templete } from './Templete'
export { default as Settings } from './Settings'